### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by vocalviews** [driftyco/ionic-push-tutorial-app#1]
You are missing $ionicPush inside:

.controller('DashCtrl', function($scope, $rootScope, $ionicUser, $ionicPush) {

**Comment by Fuiste** [comment]
Whoops, good catch there.

Fixed in https://github.com/driftyco/ionic-push-tutorial-app/commit/03fc2b1dc0da1c3e296d85bc12906f688cb0d615
