### ISSUE TITLE
 Build failed with an exception

### ISSUE THREAD

**Issue by billyjoker** [driftyco/ionic-push-tutorial-app#6]
Hi, i've followed all the setup steps but i've got an exception when i'm trying to build the project through the CLI:

D:\IONIC\push-tutorial\android>ionic build android
Running command: "C:\Program Files\nodejs\node.exe" D:\IONIC\push-tutorial\hooks\after_prepare\010_add_platform_class.js
 D:\IONIC\push-tutorial
add to body class: platform-android
Running command: cmd "/s /c "D:\IONIC\push-tutorial\platforms\android\cordova\build.bat""
ANDROID_HOME=C:\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_75
Running: D:\IONIC\push-tutorial\platforms\android\gradlew cdvBuildDebug -b D:\IONIC\push-tutorial\platforms\android\buil
d.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:

BUILD FAILED
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Total time: 2.362 secs

D:\IONIC\push-tutorial\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "D:\IONIC\push-tutorial\platforms\android\gradlew cdvBuildDebug -b D:\ION
IC\push-tutorial\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (D:\Profiles\gRaya\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\co
rdova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
...

In the other hand i've got set up and import the project with Eclipse and got run, but i'm not able to register my device...

Thanks and congratulations for your work!!

**Comment by billyjoker** [comment]
Hi again! I've resolved that issue by downloading support library from Android SDK Manager, but after that i've executed again and crash with another error related with CordovaLib:

D:\IONIC\push-tutorial\android>ionic build android
Running command: "C:\Program Files\nodejs\node.exe" D:\IONIC\push-tutorial\hooks\after_prepare\010_add_platform_class.js
 D:\IONIC\push-tutorial
add to body class: platform-android
Running command: cmd "/s /c "D:\IONIC\push-tutorial\platforms\android\cordova\build.bat""
ANDROID_HOME=C:\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_75
Running: D:\IONIC\push-tutorial\platforms\android\gradlew cdvBuildDebug -b D:\IONIC\push-tutorial\platforms\android\buil
d.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJavaD:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\CordovaClientCe
rtRequest.java:25: error: cannot find symbol
import android.webkit.ClientCertRequest;
                     ^
  symbol:   class ClientCertRequest
  location: package android.webkit
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\CordovaClientCertRequest.java:32: error: cann
ot find symbol
    private final ClientCertRequest request;
                  ^
  symbol:   class ClientCertRequest
  location: class CordovaClientCertRequest
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\CordovaClientCertRequest.java:34: error: cann
ot find symbol
    public CordovaClientCertRequest(ClientCertRequest request) {
                                    ^
  symbol:   class ClientCertRequest
  location: class CordovaClientCertRequest
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebChromeClient.java:251: error:
 cannot find symbol
    public boolean onShowFileChooser(WebView webView, final ValueCallback<Uri[]> filePathsCallback, final WebChromeClien
t.FileChooserParams fileChooserParams) {

 ^
  symbol:   class FileChooserParams
  location: class WebChromeClient
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebViewClient.java:29: error: ca
nnot find symbol
import android.webkit.ClientCertRequest;
                     ^
  symbol:   class ClientCertRequest
  location: package android.webkit
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebViewClient.java:116: error: c
annot find symbol
    public void onReceivedClientCertRequest (WebView view, ClientCertRequest request)
                                                           ^
  symbol:   class ClientCertRequest
  location: class SystemWebViewClient
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebChromeClient.java:249: error:
 cannot find symbol
    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
                                  ^
  symbol:   variable LOLLIPOP
  location: class VERSION_CODES
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java:37: error: ca
nnot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                                                        ^
  symbol:   variable LOLLIPOP
  location: class VERSION_CODES
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java:38: error: ca
nnot find symbol
            cookieManager.setAcceptThirdPartyCookies(webView, true);
                         ^
  symbol:   method setAcceptThirdPartyCookies(WebView,boolean)
  location: variable cookieManager of type CookieManager
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java:59: error: ca
nnot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                                                        ^
  symbol:   variable LOLLIPOP
  location: class VERSION_CODES
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java:60: error: ca
nnot find symbol
            cookieManager.flush();
                         ^
  symbol:   method flush()
  location: variable cookieManager of type CookieManager
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebChromeClient.java:257: error:
 cannot find symbol
                    Uri[] result = WebChromeClient.FileChooserParams.parseResult(resultCode, intent);
                                                  ^
  symbol:   variable FileChooserParams
  location: class WebChromeClient
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebChromeClient.java:250: error:
 method does not override or implement a method from a supertype
    @Override
    ^
D:\IONIC\push-tutorial\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemWebViewClient.java:114: error: m
ethod does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
14 errors
 FAILED

BUILD FAILED

Total time: 2.868 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:compileReleaseJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

D:\IONIC\push-tutorial\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "D:\IONIC\push-tutorial\platforms\android\gradlew cdvBuildDebug -b D:\ION
IC\push-tutorial\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (D:\Profiles\gRaya\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\co
rdova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by Fuiste** [comment]
From the look of these logs, it appears you haven't installed the requisite Android SDK components.

Another possibility is that Cordova's build target is a different version of the android SDK than the one you've currently installed.

**Comment by billyjoker** [comment]
Great!! My case was both you've described :dart: 

Now i can compile and execute my program succesfully, thanks!!

**Comment by Fuiste** [comment]
Glad to help!
