### ISSUE TITLE
Cannot read property 'pushNotification' of undefined

### ISSUE THREAD

**Issue by nasht00** [driftyco/ionic-push-tutorial-app#7]
I am following step-by-step directions from the tutorial.
When I click on "Register for push", I get:

```
TypeError: Cannot read property 'pushNotification' of undefined
    at Object.register (ng-cordova.js:5685)
    at init (ionic-push.js:146)
    at ionic-push.js:309
    at new Q (ionic.bundle.js:22259)
    at Q (ionic.bundle.js:22246)
    at Object.register (ionic-push.js:270)
    at Scope.$scope.pushRegister (controllers.js:41)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at ionic.bundle.js:53674
    at Scope.$eval (ionic.bundle.js:23228)(anonymous function) @ ionic.bundle.js:20434(anonymous function) @ ionic.bundle.js:17384Scope.$apply @ ionic.bundle.js:23329(anonymous function) @ ionic.bundle.js:53673eventHandler @ ionic.bundle.js:11841triggerMouseEvent @ ionic.bundle.js:2865tapClick @ ionic.bundle.js:2854tapMouseUp @ ionic.bundle.js:2927
```

**Comment by nasht00** [comment]
Following advices on gitter, I've typed:
`ionic config set dev_push true`
It seems to solve the issue.

The tutorial however states:
"By default, freshly set up apps will use the dev_push more in Ionic Push."

So, either the tutorial is wrong, or there is a bug in the platform.

**Comment by Fuiste** [comment]
Good catch @nasht00. Looks like the CLI isn't setting the `dev_push` flag correctly.  I'll make a note of it in the docs, and add that fix into the next release, but I'm going to close this issue as it isn't directly tied to the tutorial app.

**Comment by nwrman** [comment]
But what about sending push notifications to production?

When dev_push = true 

It can register with push server and the alert notification is shown on the device BUT

When dev_push = false it stops working saying "Cannot read property 'register' of undefined"

So it's weird that in production mode is not working... I'll try and look elsewhere or probably go back to previous version, when it was working fine.

**Comment by aidancasey** [comment]
I'm encountering the same problem - did you figure out the problem?

**Comment by jayrmotta** [comment]
+1

**Comment by Kailash43** [comment]
i'm also facing the same problem - Did anyone can guide me if there is any solution for this issue?

**Comment by jayrmotta** [comment]
@Kailash43 I was having this problem because I had cloned the source code but didn't execute the command to install the cordova plugins, it is like the npm and bower (in fact the dependencies are also serialized in the package.json)

If your problem is like mine you just have to type `ionic state restore` and it will read the plugins declared in the package.json.

I'm not sure if the ionic plugin command writes to the package.json by default, if it doesn't you'll have to add --save while adding the plugin again.

Hope it helps you.

Here is the link I read to figure this out: http://www.raymondcamden.com/2015/04/20/ionic-adds-a-new-state-feature

**Comment by storrisi** [comment]
Can't get out of this problem, any news?

**Comment by jayrmotta** [comment]
@storrisi have you tried any of the solutions mentioned here? dev_push, state restore...

**Comment by storrisi** [comment]
I solved using the Ionic.io instead the Angular integration.
First remember to use ionic-platform-web-client instead of ionic-service-push , which is deprecated (see at https://github.com/driftyco/ionic-service-push-client) 

Run:

    ionic add ionic-platform-web-client

Then, for production:

    ionic config set dev_push false

This is my code:
    
    Ionic.io();
    var push = new Ionic.Push();
    var user = Ionic.User.current();
        
    // if the user doesn't have an id, you'll need to give it one.
    if (!user.id) {
      user.id = Ionic.User.anonymousId();
    }
     
    user.set('name', $rootScope.user_name);
    user.set('bio', $rootScope.user_bio);
    user.save();
        		
     var callback = function(data) {
       console.log('Registered token:', data.token);
       console.log(data.token);
       push.addTokenToUser(user);
       user.save();
    }
    push.register(callback);

**Comment by nadavb** [comment]
Same problem here...
The register function simply doesn't work when I do:
ionic config set dev_push false

Help...

**Comment by jameeshpm** [comment]
I am trying to send push notification from ionic app and followed these steps http://www.sitepoint.com/push-notifications-in-ionic-apps-with-google-cloud-messaging/
i am getting error like this Uncaught TypeError: Cannot read property 'pushNotification' of undefined
this is my app.js
// Ionic Starter App
// angular.module is a global place for creating, registering and retrieving Angular modules
// 'starter' is the name of this angular module example (also set in a <body> attribute in index.html)
// the 2nd parameter is an array of 'requires'
angular.module('starter', ['ionic'])
.run(function($ionicPlatform, RequestsService) {
$ionicPlatform.ready(function() {
// Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
// for form inputs)
if(window.cordova && window.cordova.plugins.Keyboard) {
cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
}
if(window.StatusBar) {
StatusBar.styleDefault();
}
pushNotification = window.plugins.pushNotification;


window.onNotification = function(e){

  console.log('notification received');

  switch(e.event){
    case 'registered':
      if(e.regid.length > 0){

        var device_token = e.regid;
        RequestsService.register(device_token).then(function(response){
          alert('registered!');
        });
      }
      break;

    case 'message':
      alert('msg received');
      alert(JSON.stringify(e));
      break;

    case 'error':
      alert('error occured');
      break;

  }
};


window.errorHandler = function(error){
  alert('an error occured');
}


pushNotification.register(
    onNotification,
    errorHandler,
    {
      'badge': 'true',
      'sound': 'true',
      'alert': 'true',
      'senderID': '118467786675',
      'ecb': 'onNotification'
    }
);
});
})
anybody can help me with this
i am testing on real devices

**Comment by Fuiste** [comment]
@jameeshpm that guide is using an outdated version of the ionic push service.

You can find the most recent Ionic Platform docs [here](http://docs.ionic.io/docs/push-from-scratch)

**Comment by jameeshpm** [comment]
@Fuiste i hane followed all these steps and now i am getting like 
Ionic Core: init
ionic.io.bundle.min.js:2 Ionic Core: searching for cordova.js
ionic.io.bundle.min.js:2 Ionic Core: attempting to mock plugins
app.js:33 identifying user: cd3414bc-50f2-4d1a-8345-0a3db111edb6
ionic.io.bundle.min.js:2 Ionic User: saved user
app.js:37 registering push
ionic.io.bundle.min.js:2 Ionic Push: register
ionic.io.bundle.min.js:2 Ionic Push (dev): registered with development push service
ionic.io.bundle.min.js:2 Ionic Push: (debug) device token registered: <PushToken ['DEV-a90a40f8-77d0-4f05-b616-b793f1493986']>
app.js:58 registration successful
app.js:59 token: DEV-a90a40f8-77d0-4f05-b616-b793f1493986
ionic.io.bundle.min.js:2 Ionic Push: token is not a valid Android or iOS registration id. Cannot save to user.
ionic.io.bundle.min.js:2 Ionic Push (dev): watching for new notifications
ionic.io.bundle.min.js:2 Ionic User: saved user


Not able to get device token

**Comment by Fuiste** [comment]
@jameeshpm looks like you're using [development mode](http://docs.ionic.io/docs/push-development-mode), which is turned on by default in Ionic Push and is used to test correct integration with that API (or to test on a browser).

Assuming you've followed the [Android setup guide](http://docs.ionic.io/docs/push-android-setup) already, you should be able to simply turn off development mode and you'll be good to go.

**Comment by jameeshpm** [comment]
@Fuiste I have done that also, still no change. do you have any working code or tutorial, i am struggling more than one week with this

**Comment by bwoodlt** [comment]
Having the same issue, any one found a solution to this windows.plugins.pushNotification undefined issue?

**Comment by Fuiste** [comment]
@jameeshpm this repo's code is working for me locally.  If your logs are still showing a token beginning with `DEV-`, then your app is still in development mode, and needs to be set to use native pushes in order to leverage the push plugin and generate a valid token.

@bwoodlt if `windows.plugins.pushNotification`, I'd make sure that you're using the latest `ionic-platform-web-client` and `phonegap-plugin-push`, as well as ensuring that you odn't have old versions of `ionic-service-core` or `ionic-service-push` installed in your app, as those are no longer used by Ionic.

**Comment by bwoodlt** [comment]
@Fuiste What will be the latest versions for those services: 

Please see my cordova plugins:

cordova plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-geolocation 2.1.1-dev "Geolocation"
cordova-plugin-whitelist 1.1.1-dev "Whitelist"
ionic-plugin-deploy 0.4.1 "IonicDeploy"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
phonegap-plugin-push 1.5.3 "PushPlugin"

In my case, when dev_push is set to 'true', push notifications works just fine and no error was thrown. However when dev_push is set to 'false', then the windows.plugins.pushNotifications undefined error comes up.

**Comment by Fuiste** [comment]
@bwoodlt The latest version of the platform web client is 0.2.1. 

Just to verify, you're testing this on a physical device, correct (not a simulator/emulator, Ionic View, or web browser)?  

You also look like you have two different push plugins installed.  `com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"` is no longer supported by Ionic, as we've moved to the more actively maintained `phonegap-plugin-push`

**Comment by bwoodlt** [comment]
@Fuiste Have removed 2.5.0 PushPlugin and rebuilt the app. Still the same issue - push works in development but doesnt in production when dev_push is set to false.. really a tough one

**Comment by bwoodlt** [comment]
registerng-cordova.js:5932 TypeError: undefined is not an object (evaluating '$window.plugins.pushNotification')
